repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0 # Use the latest stable version
    hooks:
      - id: black
        args: ["--line-length", "88"]
        language_version: python3.11

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1 # Use a valid version tag
    hooks:
      - id: isort
        args: ["--profile", "black"]
        language_version: python3.11

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0 # Use the latest stable version
    hooks:
      - id: autopep8
        args: ["--max-line-length", "88"]
        language_version: python3.11

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4 # Use the latest stable version
    hooks:
      - id: flake8
        args: ["--max-line-length", "88"]
        language_version: python3.11
