[sources.Yahoo_Finance]
tickers = ["SPY", "UPRO"]
start_date = "2020-01-01"
end_date = "2020-12-31"

[sources.FRED]
api_key = "test_api_key"
series_ids = ["BAMLH0A0HYM2"]

[date_ranges]
start_date = "2020-01-01"
end_date = "2020-12-31"

[output]
output_dir = "data"  # Static directory for all output files

[settings]
missing_data_handling = "interpolate"
