[tool.isort]
profile = "black"               # Align with Black for compatibility
line_length = 88                # Match Black's line length
multi_line_output = 3           # Vertical hanging indentation for multiline imports
include_trailing_comma = true   # Ensure trailing commas for multiline imports
force_grid_wrap = 0             # Avoid unnecessary wrapping of imports
combine_as_imports = true       # Combine `import ... as ...` statements
balanced_wrapping = true        # Attempt to balance wrapping for readability
