name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main
      - feature/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare .env for Testing
        run: |
          cp .env.test .env
          sed -i "s|test_fred_api_key_here|${{ secrets.FRED_API_KEY }}|g" .env

      - name: Debug .env Loading
        run: |
          echo "Loaded Environment Variables:"
          cat .env
          python -c "from dotenv import load_dotenv; load_dotenv(); import os; print('FRED_API_KEY:', os.getenv('FRED_API_KEY'))"

      - name: Run All Tests
        env:
          PYTHONPATH: ${{ env.PYTHONPATH }}
        run: |
          pytest tests --maxfail=5 --disable-warnings
