name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main
      - feature/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 isort black autoflake autopep8

      - name: Run autoflake
        run: |
          autoflake --remove-unused-variables --remove-all-unused-imports --recursive --in-place src tests scripts

      - name: Run autopep8
        run: |
          autopep8 --max-line-length 88 --in-place --recursive src tests scripts

      - name: Run black
        run: |
          black --line-length 88 src tests scripts

      - name: Run isort
        run: |
          isort src tests scripts

      - name: Run flake8
        run: |
          flake8 src tests scripts

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Environment Variables
        run: |
          echo "DB_PATH=$(pwd)/data/output/aligned_data.db" >> $GITHUB_ENV
          echo "CSV_PATH=$(pwd)/data/output/generated_data.csv" >> $GITHUB_ENV
          echo "ZIPLINE_ROOT=$(pwd)/data/zipline_root" >> $GITHUB_ENV

      - name: Generate CSV Data
        run: |
          mkdir -p data/output
          python scripts/generate_csv.py

      - name: Register and Ingest Custom CSV Bundle
        run: |
          python scripts/custom_bundle.py
          zipline ingest -b custom_csv

      - name: Validate Ingestion
        run: |
          python scripts/validate_zipline_ingestion.py

      - name: Run Tests
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: |
          pytest tests/
