name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main
      - feature/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 isort black autoflake autopep8

      - name: Run autoflake
        run: |
          autoflake --remove-unused-variables --remove-all-unused-imports --recursive --in-place src tests scripts

      - name: Run autopep8
        run: |
          autopep8 --max-line-length 88 --in-place --recursive src tests scripts

      - name: Run black
        run: |
          black --line-length 88 src tests scripts

      - name: Run isort
        run: |
          isort src tests scripts

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Environment Variables
        run: |
          echo "ZIPLINE_ROOT=$(pwd)/data/zipline_root" >> $GITHUB_ENV
          export PYTHONPATH=$(pwd)/scripts:$(pwd)/src:$PYTHONPATH


      - name: Run Tests
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: |
          pytest tests/
