name: CI/CD Pipeline

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies for linting
        run: |
          python -m pip install --upgrade pip
          pip install flake8 isort black autoflake autopep8

      - name: Run autoflake
        run: |
          autoflake --remove-unused-variables --remove-all-unused-imports --recursive --in-place src tests

      - name: Run black
        run: |
          black --line-length 88 src tests

      - name: Run isort
        run: |
          isort src tests

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Environment Variables
        run: |
          echo "PYTHONPATH=$(pwd)/src:$(pwd)/tests" >> $GITHUB_ENV

      - name: Run All Tests with Coverage
        env:
          PYTHONPATH: ${{ env.PYTHONPATH }}
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: |
          pytest --cov=src --cov-report=term --cov-report=html --cov-report=xml tests/

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov/
