name: CI/CD Pipeline

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 isort black autoflake autopep8
      - name: Run autoflake
        run: |
          autoflake --remove-unused-variables --remove-all-unused-imports --recursive --in-place src tests
      - name: Run black
        run: |
          black --line-length 88 src tests
      - name: Run isort
        run: |
          isort src tests scripts
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set Environment Variables
        run: |
          echo "ZIPLINE_ROOT=$(pwd)/data/zipline_root" >> $GITHUB_ENV
          echo "PYTHONPATH=$(pwd)/src:$(pwd)/tests" >> $GITHUB_ENV
      - name: Run Configuration Tests
        env:
          PYTHONPATH: ${{ env.PYTHONPATH }}
        run: |
          pytest tests/test_parser.py --maxfail=5 --disable-warnings
          pytest tests/test_utils.py --maxfail=5 --disable-warnings
          pytest tests/test_pipelines.py --maxfail=5 --disable-warnings
      - name: Run All Tests
        env:
          PYTHONPATH: ${{ env.PYTHONPATH }}
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: |
          pytest tests --maxfail=5 --disable-warnings
